version: '3.8'
services:
  django:
    build: ./django
    command: daphne -b 0.0.0.0 -p 8000 config.asgi:application  # Daphne に変更
    ports:
      - "8000:8000"
    volumes:
      - ./src:/code
    depends_on: 
      - db
      - redis
    environment:
      - REDIS_HOST=redis
    env_file: ./django/.env

  db: 
    image: postgres:15.4 
    volumes: 
      - postgres-data:/var/lib/postgresql/data 
    environment: 
      - POSTGRES_USER=iniad 
      - POSTGRES_PASSWORD=password 
      - POSTGRES_DB=testdb 

  redis:
    image: redis:alpine
    ports: 
      - "6379:6379"

  nginx:
    image: nginx:latest     
    volumes:       
      - ./nginx/conf:/etc/nginx/conf.d      
      - ./src/collected_static:/static
      - ./nginx/ssl:/etc/nginx/ssl  # SSL 証明書のマウント
    ports:       
      - "8080:80"
      - "8443:443"     
    depends_on:       
      - django

volumes: 
  postgres-data:
