version: '3.8'
services:
  django:
    build: ./django
    command: uvicorn config.asgi:application --host 0.0.0.0 --port 8000
    expose: 
      - 8000
    volumes:
      - ./src:/code
    depends_on: 
      - db 
  db: 
    image: postgres:15.4 
    volumes: 
      - postgres-data:/var/lib/postgresql/data 
    environment: 
      - POSTGRES_USER=iniad 
      - POSTGRES_PASSWORD=password 
      - POSTGRES_DB=testdb 
  nginx:
    image: nginx:latest     
    volumes:       
      - ./nginx/conf:/etc/nginx/conf.d      
      - ./src/collected_static:/static     
    ports:       
      - 8080:80     
    depends_on:       
      - django
volumes: 
  postgres-data:

